language: python
cache: pip
dist: xenial
sudo: required
jobs:
  include:
    - name: Run plugin test suite with python 3.7
      python: 3.7
      script: |
        set -e
        pytest

    - name: Typecheck Django test suite
      python: 3.7
      script: 'python ./scripts/typecheck_tests.py'

    - name: Lint with black
      python: 3.7
      script: 'black --check --line-length=120 django-stubs/'

    - name: Lint plugin code with flake8
      python: 3.7
      script: 'flake8'

    - name: Lint plugin code with isort
      python: 3.7
      script: 'isort --check'

before_install: |
  # Upgrade pip, setuptools, and wheel
  pip install -U pip setuptools wheel
install: |
  pip install -r ./dev-requirements.txt
  pip install -r ./scripts/typecheck-tests-requirements.txt